$ErrorActionPreference='Stop'
Write-Host 'Generate and securely store the updater signing key ONCE.' -ForegroundColor Yellow
Write-Host 'Example:'
Write-Host '  npm run tauri signer generate -- -w $HOME/.tauri/mql-indicator-library.key'
Write-Host ''
Write-Host 'Then:'
Write-Host '1. Put the PUBLIC key text in src-tauri/tauri.conf.json plugins.updater.pubkey.'
Write-Host '2. Replace the release-host endpoint with the permanent HTTPS latest.json URL.'
Write-Host '3. Store TAURI_SIGNING_PRIVATE_KEY and TAURI_SIGNING_PRIVATE_KEY_PASSWORD as CI secrets.'
Write-Host '4. Never regenerate or lose the private key after users install an updater-enabled release.'
