import './styles.css';
import { open } from '@tauri-apps/plugin-dialog';
import { Command } from '@tauri-apps/plugin-shell';
import { appDataDir, join } from '@tauri-apps/api/path';
import { check } from '@tauri-apps/plugin-updater';
import { relaunch } from '@tauri-apps/plugin-process';

const state={sources:[],rows:[],stats:{total:0,mq4:0,mq5:0,review:0,duplicates:0,favorites:0},scanning:false,view:'library',search:'',platform:'ALL',category:'ALL'};
let dbPath='';

const app=document.querySelector('#app');
app.innerHTML=`<div class="app">
<aside class="sidebar"><div class="brand">MQL Indicator Library<small>Beta 0.2</small></div><div class="nav">
<button data-view="library" class="active">Library</button><button data-view="scan">Scan</button><button data-view="review">Review</button><button data-view="settings">Settings</button></div><div class="sidebar-footer" id="appStatus">Local library • Offline ready</div></aside>
<main class="main"><div class="topbar"><input id="search" class="search" placeholder="Search indicators, techniques, categories…"><button class="btn" id="refreshBtn">Refresh</button></div>
<div class="content">
<section id="library" class="view active"><div class="title-row"><div><h1>Indicator Library</h1><div class="muted">Search and organize MQ4 + MQ5 indicators by what they actually do.</div></div></div>
<div class="cards"><div class="card"><div class="muted">All Indicators</div><div class="n" id="statTotal">0</div></div><div class="card"><div class="muted">MQL4</div><div class="n" id="statMq4">0</div></div><div class="card"><div class="muted">MQL5</div><div class="n" id="statMq5">0</div></div><div class="card"><div class="muted">Review</div><div class="n" id="statReview">0</div></div><div class="card"><div class="muted">Duplicates</div><div class="n" id="statDup">0</div></div></div>
<div class="toolbar"><select id="platform"><option>ALL</option><option>MQL4</option><option>MQL5</option></select><select id="category"><option>ALL</option><option>Trend</option><option>Oscillator</option><option>Volume</option><option>Bill Williams</option><option>Volatility</option><option>Support/Resistance</option><option>Momentum</option><option>Signal</option><option>Price Action</option><option>Statistical</option><option>Utility</option><option>Unknown</option></select><span class="status" id="resultCount"></span></div>
<div class="table-wrap"><table><thead><tr><th>Name</th><th>Platform</th><th>Function</th><th>Visual</th><th>Confidence</th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty">No indicators yet. Add a folder from Scan.</div></div></section>
<section id="scan" class="view"><div class="title-row"><div><h1>Scan Library</h1><div class="muted">Add one or more folders. Existing unchanged indicators are skipped automatically.</div></div></div><div class="scan-panel"><button class="btn" id="addFolder">+ Add Folder</button><div class="sources" id="sources"></div><div><button class="btn primary" id="scanBtn">Scan Library</button></div><div class="progress"><div id="progressBar"></div></div><div class="status" id="scanText">Ready</div><div class="scan-stats"><div class="scan-stat"><div class="muted">Processed</div><b id="processed">0</b></div><div class="scan-stat"><div class="muted">Skipped</div><b id="skipped">0</b></div><div class="scan-stat"><div class="muted">Failed</div><b id="failed">0</b></div><div class="scan-stat"><div class="muted">Current</div><b id="current">0 / 0</b></div></div></div></section>
<section id="review" class="view"><div class="title-row"><div><h1>Review Queue</h1><div class="muted">Indicators with low-confidence or unknown classifications.</div></div></div><div class="review-note">Review is intentionally conservative. Confirmed decisions will become classification-memory input in the next classifier iteration.</div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Platform</th><th>Function</th><th>Visual</th><th>Confidence</th></tr></thead><tbody id="reviewRows"></tbody></table></div></section>
<section id="settings" class="view"><div class="title-row"><div><h1>Settings</h1><div class="muted">Application and update controls.</div></div></div><div class="scan-panel"><h3>Updates</h3><p class="muted">Beta builds can check for signed updates. Stable/Beta channels will be separated before production release.</p><button class="btn" id="checkUpdates">Check for Updates</button><div class="status" id="updateStatus"></div><hr style="border:0;border-top:1px solid #243041;margin:20px 0"><h3>Data</h3><div class="muted">Database location</div><div id="dbLocation" style="margin-top:7px;word-break:break-all"></div></div></section>
</div></main><aside class="detail" id="detail"><button class="btn close" id="closeDetail">×</button><div id="detailBody"></div></aside></div>`;

async function engine(args, onLine){
  const cmd=Command.sidecar('binaries/mql-engine',args);
  if(onLine){ cmd.stdout.on('data',line=>onLine(line)); cmd.stderr.on('data',line=>console.error(line)); const child=await cmd.spawn(); return child; }
  const out=await cmd.execute(); if(out.code!==0) throw new Error(out.stderr||`Engine exited ${out.code}`); return out.stdout.trim();
}
async function setup(){ const base=await appDataDir(); dbPath=await join(base,'library.sqlite3'); document.querySelector('#dbLocation').textContent=dbPath; await reloadAll(); }
async function reloadAll(){ await loadStats(); await loadRows(); await loadReview(); }
async function loadStats(){ try{const raw=await engine(['stats','--db',dbPath]); state.stats=JSON.parse(raw||'{}'); state.sources=(state.stats.sources||[]).map(s=>s.path); renderStats();renderSources();}catch(e){console.warn(e)} }
async function loadRows(){ const args=['query','--db',dbPath,'--search',state.search,'--platform',state.platform,'--category',state.category,'--limit','1000']; try{state.rows=JSON.parse(await engine(args)||'[]');renderRows();}catch(e){console.warn(e)} }
async function loadReview(){ try{const rows=JSON.parse(await engine(['query','--db',dbPath,'--review-only','--limit','1000'])||'[]'); renderTable(rows,document.querySelector('#reviewRows'));}catch(e){console.warn(e)} }
function renderStats(){statTotal.textContent=state.stats.total||0;statMq4.textContent=state.stats.mq4||0;statMq5.textContent=state.stats.mq5||0;statReview.textContent=state.stats.review||0;statDup.textContent=state.stats.duplicates||0}
function renderSources(){const el=document.querySelector('#sources'); el.innerHTML=state.sources.length?state.sources.map(s=>`<div class="source"><span>${esc(s)}</span><span class="muted">Active</span></div>`).join(''):'<div class="muted">No folders added yet.</div>'}
function renderRows(){renderTable(state.rows,document.querySelector('#rows'));document.querySelector('#resultCount').textContent=`${state.rows.length} shown`;document.querySelector('#empty').style.display=state.rows.length?'none':'block'}
function renderTable(rows,target){target.innerHTML=rows.map((r,i)=>`<tr data-idx="${i}" data-review="${target.id==='reviewRows'}"><td>${esc(r.filename)}</td><td><span class="badge">${esc(r.platform)}</span></td><td>${esc(r.primary_category)}</td><td>${esc(r.visual_category)}</td><td class="confidence ${r.confidence>=85?'high':r.confidence>=70?'med':'low'}">${r.confidence}%</td></tr>`).join(''); target.querySelectorAll('tr').forEach(tr=>tr.onclick=()=>showDetail(rows[Number(tr.dataset.idx)]));}
function showDetail(r){const tags=[...(r.secondary_categories||[]),...(r.behavior_tags||[])];detailBody.innerHTML=`<h2>${esc(r.filename)}</h2><div class="section"><div class="label">Primary Function</div><div class="value">${esc(r.primary_category)} • ${r.confidence}% confidence</div></div><div class="section"><div class="label">Visual</div><div class="value">${esc(r.visual_category)} • ${esc(r.display_location)}</div></div><div class="section"><div class="label">Platform / Source</div><div class="value">${esc(r.platform)} • ${esc(r.source_structure)}</div></div><div class="section"><div class="label">Detected Techniques & Tags</div><div class="value">${tags.map(x=>`<span class="badge" style="margin:3px">${esc(x)}</span>`).join('')||'None detected'}</div></div><div class="section"><div class="label">Built-in Indicators</div><div class="value">${(r.standard_indicators||[]).map(esc).join(', ')||'None'}</div></div><div class="section"><div class="label">File</div><div class="value" style="word-break:break-all">${esc(r.path)}</div></div>${(r.warnings||[]).length?`<div class="section"><div class="label">Warnings</div><div class="value">${r.warnings.map(esc).join('<br>')}</div></div>`:''}`;detail.classList.add('open')}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function switchView(name){state.view=name;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));}
async function addFolder(){const p=await open({directory:true,multiple:false,title:'Select MQ4/MQ5 indicator folder'});if(p&&!state.sources.includes(p)){state.sources.push(p);renderSources()}}
async function startScan(){if(!state.sources.length)return;state.scanning=true;scanBtn.disabled=true;addFolder.disabled=true;processed.textContent=skipped.textContent=failed.textContent='0';scanText.textContent='Starting scan…';progressBar.style.width='0%';const args=['scan','--db',dbPath,...state.sources.flatMap(s=>['--source',s])];try{const child=await engine(args,line=>{try{const ev=JSON.parse(line);if(ev.type==='item'||ev.type==='progress'){current.textContent=`${ev.current} / ${ev.total}`;progressBar.style.width=`${ev.total?ev.current/ev.total*100:0}%`;if(ev.processed!==undefined)processed.textContent=ev.processed;if(ev.skipped!==undefined)skipped.textContent=ev.skipped;if(ev.failed!==undefined)failed.textContent=ev.failed;scanText.textContent=ev.filename||'Scanning…'}else if(ev.type==='scan_complete'){processed.textContent=ev.processed;skipped.textContent=ev.skipped;failed.textContent=ev.failed;scanText.textContent=`Complete in ${ev.elapsed_seconds}s`;progressBar.style.width='100%'}else if(ev.type==='error'){failed.textContent=Number(failed.textContent)+1}}catch{}}); child.on('close',async()=>{state.scanning=false;scanBtn.disabled=false;addFolder.disabled=false;await reloadAll()});}catch(e){scanText.textContent=`Scan failed: ${e}`;scanBtn.disabled=false;addFolder.disabled=false;state.scanning=false}}
async function checkUpdates(){updateStatus.textContent='Checking…';try{const update=await check();if(!update){updateStatus.textContent='You are up to date.';return}updateStatus.textContent=`Version ${update.version} available. Downloading…`;await update.downloadAndInstall();updateStatus.textContent='Update installed. Restarting…';await relaunch();}catch(e){updateStatus.textContent=`Update check unavailable in this beta build: ${e}`}}

document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
search.oninput=()=>{clearTimeout(window.__st);window.__st=setTimeout(()=>{state.search=search.value;loadRows()},180)};platform.onchange=()=>{state.platform=platform.value;loadRows()};category.onchange=()=>{state.category=category.value;loadRows()};refreshBtn.onclick=reloadAll;addFolder.onclick=addFolder;scanBtn.onclick=startScan;closeDetail.onclick=()=>detail.classList.remove('open');checkUpdates.onclick=checkUpdates;
setup();
