import './styles.css';
import { Command } from '@tauri-apps/plugin-shell';
import { appDataDir, join } from '@tauri-apps/api/path';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';

const state={sources:[],rows:[],reviewRows:[],stats:{total:0,mq4:0,mq5:0,review:0,duplicates:0,verified:0},scanning:false,view:'library',search:'',platform:'ALL',category:'ALL',page:0,reviewPage:0,pageSize:250,totalRows:0,totalReview:0,folderPreview:null,browserPath:null,browserData:null};
let dbPath='';
const categories=['Trend','Oscillator','Volume','Bill Williams','Volatility','Support/Resistance','Momentum','Signal','Price Action','Market Structure','Statistical','Utility','Custom / Specialized','Composite / Multi-Purpose','Unknown'];
const app=document.querySelector('#app');
app.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">MQL Indicator Library<small>Beta 0.3.0 • Evidence Engine</small></div><div class="nav"><button data-view="library" class="active">Library</button><button data-view="scan">Scan</button><button data-view="review">Review</button><button data-view="settings">Settings</button></div><div class="sidebar-footer" id="appStatus">Local library • Offline core</div></aside><main class="main"><div class="topbar"><input id="searchBox" class="search" placeholder="Search indicators, techniques, categories…"><button class="btn" id="refreshBtn">Refresh</button></div><div class="content">
<section id="library" class="view active"><div class="title-row"><div><h1>Indicator Library</h1><div class="muted">Truth-first classification with explicit evidence and abstention.</div></div></div><div class="cards"><div class="card"><div class="muted">All Indicators</div><div class="n" id="statTotal">0</div></div><div class="card"><div class="muted">MQL4</div><div class="n" id="statMq4">0</div></div><div class="card"><div class="muted">MQL5</div><div class="n" id="statMq5">0</div></div><div class="card"><div class="muted">Needs Review</div><div class="n" id="statReview">0</div></div><div class="card"><div class="muted">Verified</div><div class="n" id="statVerified">0</div></div></div><div class="toolbar"><select id="platformFilter"><option>ALL</option><option>MQL4</option><option>MQL5</option></select><select id="categoryFilter"><option>ALL</option>${categories.map(x=>`<option>${x}</option>`).join('')}</select><span class="status" id="resultCount"></span></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Platform</th><th>Function</th><th>Status</th><th>Visual</th><th>Confidence</th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty">No indicators yet. Add a folder from Scan.</div></div><div class="pager"><button class="btn" id="prevBtn">Previous</button><span id="pageInfo" class="status"></span><button class="btn" id="nextBtn">Next</button></div></section>
<section id="scan" class="view"><div class="title-row"><div><h1>Scan Library</h1><div class="muted">Browse folders inside the app. Files remain visible while you choose the folder to scan.</div></div></div><div class="scan-panel"><button class="btn" id="addFolderBtn">+ Add Folder</button><div class="sources" id="sources"></div><div id="folderPreview" class="folder-preview"><div class="muted">No folder preview yet.</div></div><div style="margin-top:14px"><button class="btn primary" id="scanBtn">Scan Library</button></div><div class="progress"><div id="progressBar"></div></div><div class="status" id="scanText">Ready</div><div class="scan-stats"><div class="scan-stat"><div class="muted">Processed</div><b id="processed">0</b></div><div class="scan-stat"><div class="muted">Skipped</div><b id="skipped">0</b></div><div class="scan-stat"><div class="muted">Failed</div><b id="failed">0</b></div><div class="scan-stat"><div class="muted">Current</div><b id="current">0 / 0</b></div></div></div></section>
<section id="review" class="view"><div class="title-row"><div><h1>Review Queue</h1><div class="muted">Only uncertain, unverified classifications appear here.</div></div></div><div class="review-note">Unknown is a valid truthful result. Verify or correct only when you know what the indicator does.</div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Platform</th><th>Possible Function</th><th>Status</th><th>Confidence</th></tr></thead><tbody id="reviewRows"></tbody></table></div><div class="pager"><button class="btn" id="reviewPrevBtn">Previous</button><span id="reviewPageInfo" class="status"></span><button class="btn" id="reviewNextBtn">Next</button></div></section>
<section id="settings" class="view"><div class="title-row"><div><h1>Settings</h1><div class="muted">Beta 0.3.0 keeps the core offline and stores classification evidence locally.</div></div></div><div class="scan-panel"><h3>Performance</h3><p class="muted">Library browsing uses direct Rust → SQLite queries with 250-row pages. Folder previews are capped visually while still counting all files.</p><h3>Data</h3><div class="muted">Database location</div><div id="dbLocation" style="margin-top:7px;word-break:break-all"></div></div></section></div></main><aside class="detail" id="detail"><button class="btn close" id="closeDetail">×</button><div id="detailBody"></div></aside></div>
<div id="folderBrowser" class="browser-overlay hidden"><div class="browser-modal"><div class="browser-header"><div><h2>Select Folder</h2><div class="muted">Folders and files are shown together. Double-click a folder to open it.</div></div><button class="btn" id="browserClose">×</button></div><div class="browser-toolbar"><button class="btn" id="browserPc">This PC</button><button class="btn" id="browserUp">↑ Up</button><div class="browser-path" id="browserPath">This PC</div></div><div class="browser-list" id="browserList"></div><div class="browser-footer"><span class="status" id="browserStatus"></span><div><button class="btn" id="browserCancel">Cancel</button><button class="btn primary" id="browserUse">Use This Folder</button></div></div></div></div>`;

const el=id=>document.getElementById(id);
const addFolderBtn=el('addFolderBtn'),scanBtn=el('scanBtn'),processed=el('processed'),skipped=el('skipped'),failed=el('failed'),current=el('current'),scanText=el('scanText'),progressBar=el('progressBar');
async function engine(args){const cmd=Command.sidecar('binaries/mql-engine',args);const out=await cmd.execute();if(out.code!==0)throw new Error(out.stderr||`Engine exited ${out.code}`);return out.stdout.trim();}
async function ensureDb(){await engine(['stats','--db',dbPath]);}
function handleScanLine(line){try{const ev=JSON.parse(line);if(ev.type==='source_preflight'){scanText.textContent=`Preflight: ${ev.source_files||0} source files, ${ev.compiled_files||0} compiled files.`;}else if(ev.type==='scan_start'){current.textContent=`0 / ${ev.total||0}`;scanText.textContent=ev.total?`Found ${ev.total.toLocaleString()} classifiable source files.`:'No classifiable source files found.';}else if(['item','progress','error'].includes(ev.type)){current.textContent=`${ev.current||0} / ${ev.total||0}`;progressBar.style.width=`${ev.total?(ev.current/ev.total)*100:0}%`;if(ev.processed!==undefined)processed.textContent=ev.processed;if(ev.skipped!==undefined)skipped.textContent=ev.skipped;if(ev.failed!==undefined)failed.textContent=ev.failed;scanText.textContent=ev.filename||ev.error||'Scanning…';}else if(ev.type==='scan_complete'){processed.textContent=ev.processed;skipped.textContent=ev.skipped;failed.textContent=ev.failed;scanText.textContent=`Complete in ${ev.elapsed_seconds}s`;progressBar.style.width='100%';}else if(ev.type==='fatal'){scanText.textContent=`Scan failed: ${ev.error}`;}}catch(e){console.error('Invalid scanner output',line,e);}}
async function setup(){const base=await appDataDir();dbPath=await join(base,'library.sqlite3');el('dbLocation').textContent=dbPath;await listen('scan-engine-line',e=>handleScanLine(e.payload?.line??e.payload));await listen('scan-engine-stderr',e=>{const line=e.payload?.line??e.payload;console.error('scanner',line);if(state.scanning&&line)scanText.textContent=`Scanner: ${line}`;});await listen('scan-engine-done',async e=>{if(!state.scanning)return;const code=Number(e.payload?.code??-1);if(code!==0&&!scanText.textContent.startsWith('Scan failed:'))scanText.textContent=`Scan engine exited with code ${code}`;await finishScan();});await ensureDb();await reloadAll();}
async function reloadAll(){await Promise.all([loadStats(),loadRows(),loadReview()]);}
async function loadStats(){try{state.stats=await invoke('db_stats',{dbPath});if(!state.sources.length)state.sources=(state.stats.sources||[]).map(s=>s.path);renderStats();renderSources();}catch(e){console.error(e);el('appStatus').textContent=`Database error: ${e}`;}}
async function loadRows(){const offset=state.page*state.pageSize;try{const out=await invoke('db_query',{dbPath,search:state.search,platform:state.platform,category:state.category,reviewOnly:false,limit:state.pageSize,offset});state.rows=out.rows||[];state.totalRows=out.total||0;renderRows();}catch(e){console.error(e);}}
async function loadReview(){const offset=state.reviewPage*state.pageSize;try{const out=await invoke('db_query',{dbPath,search:'',platform:'ALL',category:'ALL',reviewOnly:true,limit:state.pageSize,offset});state.reviewRows=out.rows||[];state.totalReview=out.total||0;renderReview();}catch(e){console.error(e);}}
function renderStats(){el('statTotal').textContent=state.stats.total||0;el('statMq4').textContent=state.stats.mq4||0;el('statMq5').textContent=state.stats.mq5||0;el('statReview').textContent=state.stats.review||0;el('statVerified').textContent=state.stats.verified||0;}
function renderSources(){const target=el('sources');target.innerHTML=state.sources.length?state.sources.map(s=>`<div class="source"><span>${esc(s)}</span><span class="muted">Selected</span></div>`).join(''):'<div class="muted">No folder added yet.</div>';}
function renderFolderPreview(){const box=el('folderPreview');const p=state.folderPreview;if(!p){box.innerHTML='<div class="muted">No folder preview yet.</div>';return;}const shown=p.preview_files||[];box.innerHTML=`<div class="preview-head"><b>${Number(p.total_files||0).toLocaleString()} files visible to the app</b><span class="muted">${p.access_errors?`${p.access_errors} access error(s)`:''}</span></div><div class="muted preview-path">${esc(p.path)}</div><div class="preview-list">${shown.length?shown.map(f=>`<div>${esc(f)}</div>`).join(''):'<div class="muted">No files found in this folder tree.</div>'}</div>${p.total_files>shown.length?`<div class="muted preview-more">Showing first ${shown.length.toLocaleString()} of ${Number(p.total_files).toLocaleString()} files.</div>`:''}`;}
function statusClass(s){return s==='Verified'||s==='High Confidence'?'high':s==='Probable'?'med':'low';}
function renderRows(){renderTable(state.rows,el('rows'),false);el('resultCount').textContent=`${state.totalRows.toLocaleString()} matched`;el('empty').style.display=state.totalRows?'none':'block';const pages=Math.max(1,Math.ceil(state.totalRows/state.pageSize));el('pageInfo').textContent=`Page ${state.page+1} of ${pages}`;el('prevBtn').disabled=state.page===0;el('nextBtn').disabled=(state.page+1)*state.pageSize>=state.totalRows;}
function renderReview(){renderTable(state.reviewRows,el('reviewRows'),true);const pages=Math.max(1,Math.ceil(state.totalReview/state.pageSize));el('reviewPageInfo').textContent=`Page ${state.reviewPage+1} of ${pages} • ${state.totalReview.toLocaleString()} items`;el('reviewPrevBtn').disabled=state.reviewPage===0;el('reviewNextBtn').disabled=(state.reviewPage+1)*state.pageSize>=state.totalReview;}
function renderTable(rows,target,review){target.innerHTML=rows.map((r,i)=>`<tr data-idx="${i}"><td>${esc(r.filename)}</td><td><span class="badge">${esc(r.platform)}</span></td><td>${esc(r.primary_category)}</td><td><span class="confidence ${statusClass(r.classification_status)}">${esc(r.classification_status)}</span></td>${review?'':`<td>${esc(r.visual_category)}</td>`}<td class="confidence ${r.confidence>=85?'high':r.confidence>=70?'med':'low'}">${r.confidence}%</td></tr>`).join('');target.querySelectorAll('tr').forEach(tr=>tr.onclick=()=>showDetail(rows[Number(tr.dataset.idx)]));}
function evidenceHtml(items){if(!items?.length)return '<div class="muted">No reliable functional evidence recorded.</div>';return items.slice(0,30).map(e=>`<div class="evidence"><b>${esc(e.category)}</b> <span class="muted">+${esc(e.weight)}</span><br>${esc(e.detail)}</div>`).join('');}
function showDetail(r){const secondary=r.secondary_categories||[];const tags=[...(r.behavior_tags||[]),...(r.techniques||[])];const options=categories.map(c=>`<option ${c===r.primary_category?'selected':''}>${c}</option>`).join('');el('detailBody').innerHTML=`<h2>${esc(r.filename)}</h2><div class="section"><div class="label">Classification</div><div class="value">${esc(r.primary_category)} • ${r.confidence}%</div><div class="value confidence ${statusClass(r.classification_status)}">${esc(r.classification_status)}</div>${r.review_reason?`<div class="muted detail-note">${esc(r.review_reason)}</div>`:''}</div><div class="section"><div class="label">Secondary Functions</div><div class="value">${secondary.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')||'None'}</div></div><div class="section"><div class="label">Evidence</div>${evidenceHtml(r.evidence)}</div><div class="section"><div class="label">Techniques & Behavior</div><div class="value">${tags.map(x=>`<span class="badge">${esc(x)}</span>`).join(' ')||'None detected'}</div></div><div class="section"><div class="label">Visual / Source</div><div class="value">${esc(r.visual_category)} • ${esc(r.display_location)}<br>${esc(r.platform)} • ${esc(r.source_structure)}</div></div><div class="section"><div class="label">Verification</div><select id="verifyPrimary" class="detail-select">${options}</select><button id="verifyBtn" class="btn primary verify-btn">${r.human_verified?'Update Verification':'Verify / Correct'}</button><div class="muted detail-note">Verification is stored separately from machine classification and becomes classification-memory input.</div></div><div class="section"><div class="label">File</div><div class="value" style="word-break:break-all">${esc(r.path)}</div></div>${(r.warnings||[]).length?`<div class="section"><div class="label">Warnings</div><div class="value">${r.warnings.map(esc).join('<br>')}</div></div>`:''}`;el('detail').classList.add('open');el('verifyBtn').onclick=()=>verifyIndicator(r);}
async function verifyIndicator(r){const primary=el('verifyPrimary').value;try{await invoke('db_verify',{dbPath,indicatorId:r.id,primaryCategory:primary,secondaryCategories:r.secondary_categories||[]});el('detail').classList.remove('open');await reloadAll();}catch(e){alert(`Verification failed: ${e}`);}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function switchView(name){state.view=name;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));}
async function browseTo(path=null){el('browserStatus').textContent='Loading…';try{const data=await invoke('browse_directory',{path});state.browserData=data;state.browserPath=data.path==='This PC'?null:data.path;renderBrowser();}catch(e){el('browserStatus').textContent=`Cannot open folder: ${e}`;}}
function renderBrowser(){const data=state.browserData;if(!data)return;el('browserPath').textContent=data.path||'This PC';const entries=data.entries||[];el('browserStatus').textContent=`${entries.length.toLocaleString()} item${entries.length===1?'':'s'}`;el('browserUse').disabled=!state.browserPath;el('browserList').innerHTML=entries.length?entries.map((x,i)=>`<div class="browser-row ${x.kind==='folder'||x.kind==='drive'?'is-folder':'is-file'}" data-i="${i}"><span class="browser-icon">${x.kind==='drive'?'💽':x.kind==='folder'?'📁':'📄'}</span><span class="browser-name">${esc(x.name)}</span><span class="browser-kind">${x.kind==='file'?formatBytes(x.size||0):x.kind}</span></div>`).join(''):'<div class="browser-empty">This folder contains no items.</div>';el('browserList').querySelectorAll('.browser-row').forEach(row=>{const item=entries[Number(row.dataset.i)];if(item.kind==='folder'||item.kind==='drive')row.ondblclick=()=>browseTo(item.path);});}
function formatBytes(n){if(!n)return '0 B';const units=['B','KB','MB','GB'];let i=0,v=n;while(v>=1024&&i<units.length-1){v/=1024;i++;}return `${v.toFixed(i?1:0)} ${units[i]}`;}
async function openFolderBrowser(){el('folderBrowser').classList.remove('hidden');await browseTo(null);}
function closeFolderBrowser(){el('folderBrowser').classList.add('hidden');}
async function useBrowserFolder(){if(!state.browserPath)return;const p=state.browserPath;state.sources=[p];renderSources();closeFolderBrowser();scanText.textContent='Reading folder contents…';try{state.folderPreview=await invoke('folder_preview',{path:p,maxPreview:250});renderFolderPreview();scanText.textContent=`Folder ready: ${Number(state.folderPreview.total_files||0).toLocaleString()} files visible.`;}catch(e){state.folderPreview={path:p,total_files:0,preview_files:[],access_errors:1};renderFolderPreview();scanText.textContent=`Folder preview failed: ${e}`;}}
async function startScan(){if(!state.sources.length){scanText.textContent='Add a folder first.';return;}if(state.scanning)return;state.scanning=true;scanBtn.disabled=true;addFolderBtn.disabled=true;processed.textContent=skipped.textContent=failed.textContent='0';current.textContent='0 / 0';scanText.textContent='Starting scan engine…';progressBar.style.width='0%';const args=['scan','--db',dbPath,...state.sources.flatMap(s=>['--source',s])];try{await invoke('start_scan_engine',{args});}catch(e){scanText.textContent=`Scan failed to start: ${e}`;await finishScan();}}
async function finishScan(){state.scanning=false;scanBtn.disabled=false;addFolderBtn.disabled=false;state.page=0;state.reviewPage=0;await reloadAll();}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
el('searchBox').oninput=()=>{clearTimeout(window.__st);window.__st=setTimeout(()=>{state.search=el('searchBox').value;state.page=0;loadRows();},180);};
el('platformFilter').onchange=()=>{state.platform=el('platformFilter').value;state.page=0;loadRows();};el('categoryFilter').onchange=()=>{state.category=el('categoryFilter').value;state.page=0;loadRows();};
el('refreshBtn').onclick=reloadAll;addFolderBtn.onclick=openFolderBrowser;scanBtn.onclick=startScan;el('closeDetail').onclick=()=>el('detail').classList.remove('open');
el('prevBtn').onclick=()=>{if(state.page>0){state.page--;loadRows();}};el('nextBtn').onclick=()=>{if((state.page+1)*state.pageSize<state.totalRows){state.page++;loadRows();}};
el('reviewPrevBtn').onclick=()=>{if(state.reviewPage>0){state.reviewPage--;loadReview();}};el('reviewNextBtn').onclick=()=>{if((state.reviewPage+1)*state.pageSize<state.totalReview){state.reviewPage++;loadReview();}};
el('browserClose').onclick=closeFolderBrowser;el('browserCancel').onclick=closeFolderBrowser;el('browserPc').onclick=()=>browseTo(null);el('browserUp').onclick=()=>{if(state.browserData?.parent)browseTo(state.browserData.parent);else browseTo(null);};el('browserUse').onclick=useBrowserFolder;
setup();